esphome:
  name: hcpbridge

external_components:
  - source:
      type: local
      path: "../components/"

esp32:
  board: esp32-s3-devkitc-1

wifi:
  ssid: "My Network"
  password: "My Password"

uart:
  tx_pin: GPIO17
  rx_pin: GPIO18
  baud_rate: 57600
  data_bits: 8
  stop_bits: 1
  parity: EVEN

hcpbridge:
  id: hcpbridge_id

cover:
  - platform: hcpbridge

binary_sensor:
  - platform: hcpbridge

light:
  - platform: hcpbridge
